name: Test Dev
author: 'Aman Shankar Sharma'
description: 'Build and test the development branch on PR events'

on:
  pull_request:
    types: [assigned, opened, synchronize, edited, reopened]
    branches:
      - development
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        default: '1.0.0'
        required: true
      build-number:
        description: 'Build number'
        default: '1'
        required: true

jobs:
  test:
    name: Testing
    runs-on: macos-11.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Initialise submodule via script
        run:  ./.github/scripts/init-submodules.sh
      - name: Force XCode 12.2
        run:  sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: Testing the app
        run:  ./.github/scripts/test-dev.sh
#       - name: Gather coverage
#         run:  ./.github/scripts/slather-out.sh
